name: artifacts

on:
  push:
    branches: [main]
    tags:
      - "**"
      - "!**-artifacts"

env:
  FOUNDRY_PROFILE: ci

jobs:
  artifacts:
    name: Artifacts generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: nightly

      - name: Generate artifacts and push as new tag
        run: bash .github/scripts/release-artifacts.sh "$GITHUB_REF"
